# Stage 1: Build the Angular application
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --force

COPY . .

RUN npm run build:prod-new

# Stage 2: Serve with Nginx
FROM nginx:alpine

COPY --from=build /app/dist/commerce-castle /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
