export const internationalisationKeys = {
    name: 'name',
    email: 'email',
    phoneNumber: 'phoneNumber',
    password: 'password',
    register: 'register',
    login: 'login',
    logout: 'logout',
    cancel: 'cancel',
    verify: 'verify',
    edit: 'edit',
    amount: 'amount',
    description: 'description',
    type: 'type',
    loadMore: 'loadMore',
    
    addToCart: 'addToCart',

    forgotPassword: 'forgotPassword',
    resetPassword: 'resetPassword',
    newPassword: 'newPassword',

    myAccount: 'myAccount',
    myOrders: 'myOrders',
    myFavorites: 'myFavorites',
    myAddresses: 'myAddresses',
    myNotifications: 'myNotifications',
    myWallet: 'myWallet',
    myReferral: 'myReferral',
    myProfile: 'myProfile',
    addNewAddress: 'addNewAddress',

    continueShopping: 'continueShopping',
    downloadApp: 'downloadApp',
    search: 'search',
    cart: 'cart',
    continueToCheckout: 'continueToCheckout',
    applyCoupon: 'applyCoupon',
    apply: 'apply',
    summary: 'summary',
    total: 'total',
    deliveryFee: 'deliveryFee',
    couponDiscount: 'couponDiscount',
    discount: 'discount',
    tax: 'tax',
    subTotal: 'subTotal',
    orderSummary: 'orderSummary',
    shoppingCart: 'shoppingCart',
    poweredBy: 'poweredBy',
    subscribeNow: 'subscribeNow',
    newsletter: 'newsletter',
    selectDeliveryLocation: 'selectDeliveryLocation',
}