export const internationalisationKeys = {
    addNewAddress: 'addNewAddress',
    acknowledgement: 'acknowledgement',
    acknowledgementparagraphone: 'acknowledgementParagraphOne',
    acknowledgementparagraphtwo: 'acknowledgementParagraphTwo',
    acknowledgementbutton: 'acknowledgementButton',
    addToCart: 'addToCart',
    updateCart: 'updateCart',
    deleteFromCart: 'deleteFromCart',
    updateAddOn: 'updateAddOn',
    amount: 'amount',
    apply: 'apply',
    applyCoupon: 'applyCoupon',
    cancel: 'cancel',
    cart: 'cart',
    clear: 'clear',
    continueShopping: 'continueShopping',
    continueToCheckout: 'continueToCheckout',
    continue: 'continue',
    reorder: 'reorder',
    couponApplied: 'couponApplied',
    couponCode: 'couponCode',
    couponDiscount: 'couponDiscount',
    couponDiscountText: 'couponDiscountText',
    deliveryAddress: 'deliveryAddress',
    deliveryFee: 'deliveryFee',
    description: 'description',
    discount: 'discount',
    downloadApp: 'downloadApp',
    edit: 'edit',
    message: 'message',
    submit: 'submit',
    items: 'items',
    rating: 'rating',
    remove: 'remove',
    or: 'or',
    orderNo: 'orderNo',
    placedOn: 'placedOn',
    viewDetails: 'viewDetails',
    quantity: 'quantity',
    orderDetails: 'orderDetails',
    viewStatus: 'viewStatus',
    hideStatus: 'hideStatus',
    addReview: 'addReview',
    deliveredTo: 'deliveredTo',
    paymentMethod: 'paymentMethod',
    orderSummary: 'orderSummary',
    priceDetails: 'priceDetails',
    additionalCharge: 'additionalCharge',
    alreadyInCart: 'alreadyInCart',
    price: 'price',
    email: 'email',
    forgotPassword: 'forgotPassword',
    inclusiveOfVat: 'inclusiveOfVat',
    loadMore: 'loadMore',
    login: 'login',
    logout: 'logout',
    myAccount: 'myAccount',
    myAddresses: 'myAddresses',
    myFavorites: 'myFavorites',
    myNotifications: 'myNotifications',
    myOrders: 'myOrders',
    myProfile: 'myProfile',
    myReferral: 'myReferral',
    myWallet: 'myWallet',
    name: 'name',
    newPassword: 'newPassword',
    newsletter: 'newsletter',
    password: 'password',
    phoneNumber: 'phoneNumber',
    placeOrder: 'placeOrder',
    poweredBy: 'poweredBy',
    register: 'register',
    resetPassword: 'resetPassword',
    search: 'search',
    selectDeliveryLocation: 'selectDeliveryLocation',
    shippingNote: 'shippingNote',
    shoppingCart: 'shoppingCart',
    subTotal: 'subTotal',
    subscribeNow: 'subscribeNow',
    summary: 'summary',
    tax: 'tax',
    total: 'total',
    type: 'type',
    verify: 'verify',
    walletDiscount: 'walletDiscount',
    wishList: 'wishList',
    resetyourpasswordtext:'resetyourpasswordtext',
    emailAddress: 'emailAddress',
    invalidEmailAddress: 'invalidEmailAddress',
    emailIsRequired: 'emailIsRequired',
    passwordLink: 'passwordLink',
    accountNotFound: 'accountNotFound',
    contactusNow: 'contactusNow',
    contactusText:'contactusText',
    giveFeedback:'giveFeedback',
    customerSupport: 'customerSupport',
    whatsapp: 'whatsapp',
    freeConsultations: 'freeConsultations',
    enableProductfooter: 'enableProductfooter',
    wideRange: 'wideRange',
    morethanProductsfooter: 'morethanProductsfooter',
    freeDelivery: 'freeDelivery',
    forOrdersMorefooter: 'forOrdersMorefooter',
    returnProcess: 'returnProcess',
    easyAndFast: 'easyAndFast',
    newsletterandNotify:'newsletterandNotify',
    findMore:'findMore',
    personalCare: 'personalCare',
    basicsofPregnancy: 'basicsofPregnancy',
    momsPacklist:'momsPacklist',
    theChild:'theChild',
    theAccount: 'theAccount',
    whoarewe: 'whoarewe',
    contactus: 'contactus',
    deliveryPolicy: 'deliveryPolicy',
    returnPolicy:'returnPolicy',
    blogs: 'blogs',
    termsandConditions: 'termsandConditions',
    privacypolicy: 'privacypolicy',
    allrightreserved: 'allrightreserved',
    noAddressFound: 'noAddressFound',
    emptyFavourites: 'emptyFavourites',
    noOrders: 'noOrders',
    noNotifications: 'noNotifications',
    screenYourShoppingCartIsEmpty: 'screenYourShoppingCartIsEmpty',
    yourEmailAddress: 'yourEmailAddress',
    subscribe: 'subscribe',
    findTheProductsYouAreLookingfor: ' findTheProductsYouAreLookingfor',
    pleaseEnteravalidOTP: 'pleaseEnteravalidOTP',
    placed: 'placed',
    accepted: 'accepted',
    packed: 'packed',
    shipped: 'shipped',
    outForDelivery: 'outForDelivery',
    deliveried: 'deliveried',
    cancelled: 'cancelled',
    updateVersionTitle: 'updateVersionTitle',
    updateVersionDescription: 'updateVersionDescription',
    failed: 'failed',
    nameisRequired: 'nameisRequired',
    findOutMoreAt: 'Find out more at',
    phoneNumberisrequired: 'phoneNumberisrequired',
    invalidPhoneNumber: 'invalidPhoneNumber',
    save: 'save',
    verificationEmail: 'verificationemail',
    checkEmailForFurthur: 'checkEmailForFurthur',
    somethingWrong: 'somethingWrong',
    ProfileUpdated: 'ProfileUpdated',
    sessionExpired: 'sessionExpired',
    loginuseOtp: 'loginuseOtp',
    emailorNumber: 'emailorNumber',
    noCategoryFound: 'noCategoryFound',
    loginWithOtp: 'loginWithOtp',
    forgetEmail: 'forgetEmail',
    deleteAll: 'deleteAll',
    filter: 'filter',
    categories: 'categories',
    age: 'age',
    color: 'color',
    recommendedAge: 'recommendedAge',
    brand: 'brand',
    sortBy: 'sortBy',
    fullName: 'fullName',
    referralCode: 'referralCode',
    enterYourPassword: 'enterYourPassword',
    passwordIsRequired: 'passwordIsRequired',
    showallProductsFrom: 'showallProductsFrom',
    similarProducts: 'similarProducts',
    recommended: 'recommended',
    ratingAndReviews: 'ratingAndReviews',
    details: 'details',
    freeShipping: 'freeShipping',
    insuredInstalments: 'insuredInstalments',
    orderBefore: 'orderBefore',
    cantBeReturned: 'cantBeReturned',
    share: 'share',
    getDeliveryBy: 'getDeliveryBy',
    enterEmailorMobile: 'enterEmailorMobile',
    enterEmailorMobileValid: 'enterEmailorMobileValid',
    otp: 'otp',
    enterOtp: 'enterOtp',
    enterOtpValid: 'enterOtpValid',
    loginWithPassword: 'loginWithPassword',
    enterTheOtp: 'enterTheOtp',
    freequentlyAsked: 'freequentlyAsked',
    findQuickAnswerFAQ: 'findQuickAnswerFAQ',
    group: 'group',
    noProductsFound: 'noProductsFound',
    selectAnOption: 'selectAnOption',
    shipMyOrderToMyGivenAddress: 'shipMyOrderToMyGivenAddress',
    changes: 'changes',
    premium: 'premium',
    cardOnDelivery: 'cardOnDelivery',
    someItemNotCOD: 'someItemNotCOD',
    cod: 'cod',
    saveCard: 'saveCard',
    howDoYouWanttoPay: 'howDoYouWanttoPay',
    selectPickupLocation: 'selectPickupLocation',
    shippingInstructions: 'shippingInstructions',
    collectFromOurOutlet: 'collectFromOurOutlet',
    clickAndCollect: 'clickAndCollect',
    cartEmpty: 'cartEmpty',
    availablePayments: 'availablePayments',
    recentlyBought: 'recentlyBought',
    products: 'products',
    changeYourPassword: 'changeYourPassword',
    readMore: 'readMore',
    blog: 'blog',
    cityIsRequired: 'cityIsRequired',
    city: 'city',
    stateIsRequired: 'stateIsRequired',
    state: 'state',
    streetIsRequired: 'streetIsRequired',
    streetName: 'streetName',
    street: 'street',
    apartmentIsrequired: 'streetIsrequired',
    apartmentDetails: 'apartmentDetails',
    apartment: 'apartment',
    requiredLengthNumber: "requiredLengthNumber",
    mobileRequired: 'mobileRequired',
    fullNameRequired: 'fullNameRequired',
    other: 'other',
    office: 'office',
    currentLocation: 'currentLocation',
    confirmLocation: 'confirmLocation',
    previousSlide: 'previousSlide',
    nextSlide: 'nextSlide',
    freeDeliveryText: 'freeDeliveryText',
    sku: 'sku',
    wallet: 'wallet',
    walletBalance: 'walletBalance',
    myCart: 'myCart',
    profile: 'profile',
    logoutText: 'logoutText',
    myFavourites: 'myFavourites',
    continueAsGuest: 'continueAsGuest',
    time: 'time',
    left: 'left',
    theMom: 'theMom',
    itemRemovedFromCart: 'itemRemovedFromCart',
    itemAddedToCart: 'itemAddedToCart',
    pleaseSelectDeliveryAddress: 'pleaseSelectDeliveryAddress',
    orderPlacedSuccessfully: 'orderPlacedSuccessfully',
    payment: 'payment',
    confirmationMail: 'confirmationMail',
    yourOrderReference: 'yourOrderReference',
    immediateConcern: 'immediateConcern',
    somethingWentWrong: 'somethingWentWrong',
    delivered: 'delivered',
    viewAllProductsFrom: 'viewAllProductsFrom',
    theDetails: 'theDetails',
    followYourRequest: 'followYourRequest',
    address: 'address',
    billingAddress: 'billingAddress',
    orderProcessedText: 'orderProcessedText',
    thankYouForPurchase: 'thankYouForPurchase',
    cancelOrder: 'cancelOrder',
    messageIsRequired: 'messageIsRequired',
    writeMessageHere: 'writeMessageHere',
    AddressTypeRequired: 'AddressTypeRequired',
    forgetPassword: 'forgetPassword',
    didYouForgetPassword: 'didYouForgetPassword',
    phoneNumberInvalid: 'phoneNumberInvalid',
    updatedDefaultAddress: 'updatedDefaultAddress',
    itemhasBeenRemovedfromCart: 'itemhasBeenRemovedfromCart',
    emailVerifiedSuccessfully: 'emailVerifiedSuccessfully',
    emailVerified: 'emailVerified',
    yourEmailHasbeenVerifiedSuccessfully: 'yourEmailHasbeenVerifiedSuccessfully',
    emailVerifiedFailed: 'emailVerifiedFailed',
    pleaseWait: 'pleaseWait',
    verifyingYourEmail: 'verifyingYourEmail',
    gotoHome: 'gotoHome',
    updateYourAddress: 'updateYourAddress',
    addingYourAddress: 'addingYourAddress',
    addressDeletedSuccessfully: 'addressDeletedSuccessfully',
    otpSendto: 'otpSendto',
    verifyOtp: 'verifyOtp',
    notRecievedCode: 'notRecievedCode',
    resendCode: 'resendCode',
    newArrivals: 'newArrivals',
    successSubmit: 'successSubmit',
    noCoupons: 'noCoupons',
    low: 'low',
    high: 'high',
    confirm: 'confirm',
    off: 'off',
    preview: 'preview',
    yourRefereal: 'yourRefereal',
    referFriend: 'referFriend',
    copyRefer: 'copyRefer',
    referTitle: 'referTitle',
    extraInfo: 'extraInfo',
    noPickupService: 'noPickupService',
    walletBalence: 'walletBalence',
    transactionHistory: 'transactionHistory',
    noHistoryFound: 'noHistoryFound',
    transactionid: 'transactionid',
    min: 'min',
    max: 'max',
    collections: 'collections',
    popularity: 'popularity',
    priceLtoH: 'priceLtoH',
    priceHtoL: 'priceHtoL',
    nameZtoA: 'nameZtoA',
    nameAtoZ: 'nameAtoZ',
    tenPercent: 'tenPercent',
    twentyPercent: 'twentyPercent',
    tirtyPercent: 'tirtyPercent',
    fourtyPercent: 'fourtyPercent',
    fiftPercent: 'fiftPercent',
    origins: 'origins',
    subscribeToOur: 'subscribeToOur',
    sureToDelete: 'sureToDelete',
    sureToLogout: 'sureToLogout',
    work: 'work',
    others: 'others',
    brands: 'brands',
    sort: 'sort',
    filters: 'filters',
    ifollowYourRequest: 'ifollowYourRequest',
    useCurrentLocation: 'useCurrentLocation',
    shipToAddress: 'shipToAddress',
    sheduleTime: 'sheduleTime',
    noItemsFound: 'noItemsFound',
    done: 'done',
    orderSuccess: 'orderSuccess',
    thankyouPurchase: 'thankyouPurchase',
    orderProcessNote: 'orderProcessNote',
    selectAddresstype: 'selectAddresstype',
    selectDateTime: 'selectDateTime',
    loggedinSuccess: 'loggedinSuccess',
    loggedoutSuccess: 'loggedoutSuccess',
    success: 'success',
    acceptTerms: 'acceptTerms',
    prodctSeemsOutofStock: 'prodctSeemsOutofStock',
    deleteAddess: 'deleteAddess',
    yes: 'yes',
    no: 'no',
    sendMessage: 'sendMessage',
    sheduleDate: 'sheduleDate',
    clickCollect: 'clickCollect',
    collectFromOutlet: 'collectFromOutlet',
    defalutAddress: 'defalutAddress',
    pressAgain: 'pressAgain',
    productDetails: 'productDetails',
    selectRating: 'selectRating',
    subscribedNewsletter: 'subscribedNewsletter',
    codNotAvailable: 'codNotAvailable',
    pleaseAddAddress: 'pleaseAddAddress',
    allBrands: 'allBrands',
    searchForBrands: 'searchForBrands',
    selectEmirateCity: 'selectEmirateCity',
    orderDate: 'orderDate',
    order: 'order',
    date: 'date',
    choosePaymentType: 'choosePaymentType',
    myOrderDetails: 'myOrderDetails',
    deliveryDetails: 'deliveryDetails',
    sureWantToDelete: 'sureWantToDelete',
    enterPhoneorMail: 'enterPhoneorMail',
    thisFeildRequired: 'thisFeildRequired',
    filterBy: 'filterBy',
    loginWith: 'loginWith',
    youSaved: 'youSaved',
    availablePaymentMethods: 'availablePaymentMethods',
    paymentMethods: 'paymentMethods',
    youNeedMoreAmount: 'youNeedMoreAmount',
    forOnlineService: 'forOnlineService',
    send: 'send',
    enter: 'enter',
    isRequired: 'isRequired',
    enterValid: 'enterValid',
    delete: 'delete',
    outOfStock: 'outOfStock',
    purchasemoreFrom: 'purchasemoreFrom',
    insuredPremium: 'insuredPremium',
    orderBefor: 'orderBefor',
    noDescription: 'noDescription',
    tooShort: 'tooShort',
    referal: 'referal',
    optional: 'optional',
    more: 'more',
    guest: 'guest',
    cartEmptyText: 'cartEmptyText',
    freeDeliver: 'freeDeliver',
    update: 'update',
    requestSubmitted: 'requestSubmitted',
    giveusRating: 'giveusRating',
    review: 'review',
    faq: 'faq',
    aboutUs: 'aboutUs',
    newslettre: 'newslettre',
    account: 'account',
    category: 'category',
    all: 'all',
    coupons: 'coupons',
    typeCodeHere: 'typeCodeHere',
    deliveryMethod: 'deliveryMethod',
    noPickUp: 'noPickUp',
    checkout: 'checkout',
    shippingNotes: 'shippingNotes',
    landmark: 'landmark',
    shipping: 'shipping',
    additionalCharges: 'additionalCharges',
    writeReview: 'writeReview',
    status: 'status',
    first: 'first',
    last: 'last',
    next: 'next',
    select: 'select',
    qty: 'qty',
    passwordInstructionMessage: 'passwordInstructionMessage',
    passwordLengthMessage: 'passwordLengthMessage',
    viewProducts: 'viewProducts',
    inCategories: 'inCategories',
    searchkeyword: 'searchkeyword',
    backToLogin: 'backToLogin',
    deliveryDate: 'deliveryDate',
    deliveryTime: 'deliveryTime',
    homeDashboard: 'homeDashboard',
    homeAddress: 'homeAddress',
    myVouchers: 'myVouchers',
    someItemsUnavailable:'someItemsUnavailable',
    noTransactions:'noTransactions',
    redeemVoucher:'redeemVoucher',
    enterVoucherCode:'enterVoucherCode',
    redeem:'redeem',
    confirmDeleteAddress:'confirmDeleteAddress',
    confirmDeletemessage:'confirmDeletemessage',
    updateAddress:'updateAddress',
    failedToCopyURL:'failedToCopyURL',
    referralcodeCopied:'referralcodeCopied',
    removeWalletDiscount:'removeWalletDiscount',
    addWalletDiscount:'addWalletDiscount',
    walletUsedMessage:'walletUsedMessage',
    firstLane:'firstLane',
    firstLaneIsRequired:'firstLaneIsRequired',
    area:'area',
    areaIsRequired:'areaIsRequired',
    phnNumberCount:'phnNumberCount',
    streetAddress:'streetAddress',
    landmarkIsRequired:'landmarkIsRequired',
    country:'country',
    selectCountry:'selectCountry',
    searchCountry:'searchCountry',
    noCountryFound:'noCountryFound',
    countryRequired:'countryRequired',
    emirates:'emirates',
    selectEmirates:'selectEmirates',
    searchEmirates:'searchEmirates',
    noEmiratesFound:'noEmiratesFound',
    emirateIsRequired:'emirateIsRequired',
    selectArea:'selectArea',
    searchArea:'searchArea',
    noAreaFound:'noAreaFound',
    setAsDefault:'setAsDefault',
    saveAddress:'saveAddress',
    apartmentVilla:'apartmentVilla',
    apartmentVillaIsRequired:'apartmentVillaIsRequired',
    officeIsRequired:'officeIsRequired'
}
