export const toastKeys = {
    loginSuccess: 'loginSuccess',
    loginFailed: 'loginFailed',
    logoutSuccess: 'logoutSuccess',
    logoutFailed: 'logoutFailed',
    registerSuccess: 'registerSuccess',
    registerFailed: 'registerFailed',
    forgotPasswordSuccess: 'forgotPasswordSuccess',
    forgotPasswordFailed: 'forgotPasswordFailed',
    resetPasswordSuccess: 'resetPasswordSuccess',
    resetPasswordFailed: 'resetPasswordFailed',
    updatePasswordSuccess: 'updatePasswordSuccess',
    updatePasswordFailed: 'updatePasswordFailed',
    updateProfileSuccess: 'updateProfileSuccess',
    updateProfileFailed: 'updateProfileFailed',
    updateAddressSuccess: 'updateAddressSuccess',
    updateAddressFailed: 'updateAddressFailed',
    deleteAddressSuccess: 'deleteAddressSuccess',
    deleteAddressFailed: 'deleteAddressFailed',
    addAddressSuccess: 'addAddressSuccess',
    addAddressFailed: 'addAddressFailed',
    addToCart: 'addToCart',
    removeFromCart: 'removeFromCart',
    availableInLimitedQuantity: 'availableInLimitedQuantity',
    updateCart: 'updateCart',
    clearCart: 'clearCart',    
    updateWishlist: 'updateWishlist',
    addProductToWishlist:  'addProductToWishlist',
    removeProductFromWishlist: 'removeProductFromWishlist',   
     addProductToCompare: 'addProductToCompare',
    removeProductFromCompare: 'removeProductFromCompare',
    placeOrder: 'placeOrder',
    notifyMe: 'notifyMe',
    limitedStock: 'limitedStock',
    forgottenPasswordToast : 'forgottenPasswordToast',
    invalidUser:'invalidUser',
    incorrectPassword:'incorrectPassword',
    registerdEmail:'registerdEmail',
    registerdPhoneNumber:'registerdPhoneNumber',
    subscribedSuccessfully:'subscribedSuccessfully',
    alreadySubscribed:'alreadySubscribed',
    inactiveUser:'inactiveUser',
    noWalletBalance:'noWalletBalance',
    youHave:'youHave',
    availableinWallet:'availableinWallet',
    
    // Cart Page Messages
    couponAppliedSuccess: 'couponAppliedSuccess',
    couponNotFound: 'couponNotFound',
    couponExpired: 'couponExpired',
    couponNotValidForLimit: 'couponNotValidForLimit',
    
    // Wallet Messages
    walletUpdated: 'walletUpdated',
    
    // Order Status Messages
    orderDelivered: 'orderDelivered',
    orderDeliveredSuccess: 'orderDeliveredSuccess',
    orderShipped: 'orderShipped',
    orderShippedSuccess: 'orderShippedSuccess',
    orderPacked: 'orderPacked',
    orderPackedSuccess: 'orderPackedSuccess'
}