// export const iraqStates = [
//     { state: "Baghdad", cities: [] },
//     { state: "Basra", cities: [] },
//     { state: "Nineveh", cities: [] },
//     { state: "Erbil", cities: [] },
//     { state: "Sulaymaniyah", cities: [] },
//     { state: "Diyala", cities: [] },
//     { state: "Anbar", cities: [] },
//     { state: "Karbala", cities: [] },
//     { state: "Wasit", cities: [] },
//     { state: "Salah ad-Din", cities: [] },
//     { state: "Najaf", cities: [] },
//     { state: "Qadisiyah", cities: [] },
//     { state: "Maysan", cities: [] },
//     { state: "Babylon", cities: [] },
//     { state: "Dhi Qar", cities: [] },
//     { state: "Kirkuk", cities: [] },
//     { state: "Muthanna", cities: [] },
//     { state: "Babil", cities: [] },
//     { state: "Duhok", cities: [] },
//     { state: "Salahuddin", cities: [] },
//   ];

export const iraqStates = [
  { state: "أربيل", cities: [] },
  { state: "الأنبار", cities: [] },
  { state: "بابل", cities: [] },
  { state: "بصرة", cities: [] },
  { state: "بغداد", cities: [] },
  { state: "دهوك", cities: [] },
  { state: "موصل", cities: [] },
  { state: "البصرة", cities: [] },
  { state: "ديالى", cities: [] },
  { state: "سليمانية", cities: [] },
  { state: "ناصرية", cities: [] },
  { state: "صلاح الدين", cities: [] },
  { state: "اربيل", cities: [] },
  { state: "قادسية", cities: [] },
  { state: "كربلاء", cities: [] },
  { state: "كركوك", cities: [] },
  { state: "مثنى", cities: [] },
  { state: "نيويه", cities: [] },
  { state: "ميسان", cities: [] },
  { state: "دى قار", cities: [] },
  { state: "نجف", cities: [] },
  { state: "واسط", cities: [] },
  { state: "سلطان عدن", cities: [] },
];