export const adminUsersEndpoints = {
     get_admin_users: '/admin-users',
     get_admin_user: '/admin-user',
     addAdmin: '/add-admin',
     updateAdmin: '/update-admin',
     update_admin: '/update-admin-user',
     get_admin_count: '/get-admin-mail',
     admin_details: '/admin-details',
     search_admins: '/search-admins',
     authorize: '/authorize',
     general_seearch: '/search',
     reset_admin_password: '/reset-admin-password',
     subscribeAdmin: '/subscribe-admin',
     forgotPassword: '/forgot-password',
     resetPassword: '/reset-password',
     resetToken: '/reset-token',
     duplicateEmail: '/duplicate-email',
     deleteAdmin: '/delete-admin',
     updateAdminEmail: '/update-admin-email',
     updateAdminMobile: '/update-admin-mobile',
     changePassword: '/change-password'
}