export const categoryEndpoints = {
  add_category: '/add-category',
  get_category: '/categories',
  get_category_page: '/categories-page',
  get_active_categories: '/categories/active',
  get_category_by_slug: '/category',
  update_category: '/update-category',
  get_category_count: '/categories/count',
  search_category: '/categories/search',
  get_main_categories: '/main-categories',
  get_sub_categories: '/sub-categories',
  archive_category: '/categories/archive',
  restore_category: '/categories/restore',
  get_sub_categories_by_id: '/sub-categories-id',
  all_sub_categories: '/all-sub-categories',
  category_images: '/categories/images',
  category_bulk_file_upload: '/categories/bulk-file-upload',
  categories_bulk_image_upload: '/categories/bulk-image-upload',
  find_categories: '/find-categories',
  mega_categories: '/mega-categories',
  get_categories: '/get-categories',
  childCategories: '/child-categories',
  updateCategoryMedias: '/update-category-media',
  removeCategoryMedia: '/remove-category-cover',
  dropdownCategories: '/dropdown-categories',
  defaultCategories: '/default-categories'
}
