export const categoryEndpoints = {
  add_category: '/add-category',
  get_category: '/categories',
  get_active_categories: '/active-categories',
  getCategoryDetails: '/category',
  update_category: '/update-category',
  deleteCategory: '/delete-category',
  restoreCategory: '/restore-category',
  search_category: '/search-categories',
  get_main_categories: '/main-categories',
  get_sub_categories: '/sub-categories',
  archived_categories: '/archived-categories',
  get_subcategories_details: '/subcategory-details',
  category_bulk_file_upload: '/categories/bulk-file-upload',
  categories_bulk_image_upload: '/categories/bulk-image-upload',
  find_categories: '/find-categories',
  mega_categories: '/mega-categories',
  get_categories: '/get-categories',
  childCategories: '/child-categories',
  dropdownCategories: '/dropdown-categories',
  defaultCategories: '/default-categories'
}
