export const customerEndpoints = {
  add_customer: '/customer/create',
  get_customer: '/customer/get-customers',
  get_active_customers: '/customer/get-customer/active',
  get_customer_by_mail: '/customer/mail',
  get_customer_count: '/customers/count',
  get_customer_by_slug: '/customer/slug',
  update_customer: '/customer/update',
  get_customer_by_number: '/customer/number',
  search_customers: '/search-customers',
  add_address: '/add-address',
  get_address: '/get-address',
  address_details: '/address-details',
  manage_address: '/manage-address',
  download_customers: '/download-customers',
  wishlist: '/wishlist',
  wishlist_details: '/wishlist-details',
}
