export const dashboardEndpoints = {
  dashboard: '/dashboard',
  monthly_revenue: '/monthly-revenue',
  days_revenue: '/daily-revenue',
  top_selling_products: '/top-selling-products',
  new_orders: '/new-orders',
  publish_dashboard: '/publish-dashboard',
  preview_dashboard: '/preview-dashboard',
  dashboard_config: '/dashboard-config',
  currentRevenues: '/current-revenues',
  sourceDetails: '/source-details',
  monthlyComparison: '/monthly-comparison',
  salesAnalytics: '/sales-analytics',
  sales: '/sales',
  storeTips: '/store-tips',
}
