export const orderEndpoints = {
   add_order: '/create-order',
   get_order: '/orders',
   list_orders:'/list-orders',
   bulk_orders: '/bulk-orders',
   get_pending_orders: '/orders/pending',
   get_pending_orders_by_orderNo: '/orders/pending/number',
   get_active_order: '/orders/active',
   update_order: '/update-order',
   get_order_by_orderno: '/orders/number',
   get_order_by_refid: '/orders/refid',
   get_order_count: '/orders/count',
   getInvoiceSignedUrl: '/getInvoiceSignedUrl',
   getPackingSlipSignedUrl: '/getPackingSlipSignedUrl',
   getInvoicesSignedUrl: '/getInvoicesSignedUrl',
   getPackingSlipsSignedUrl: '/getPackingSlipsSignedUrl',
   detailed_report: '/detailed-order-report',
   search_order: '/orders/search',
   search_pending_orders: '/orders/pending/search',
   order_details: '/order-details',
   getStatusList: '/status-list',
   updateOrderStatus: '/update-status',
   cancelOrderDetails: '/cancel-order-details',
   updateOrderProducts: '/update-order-products',
   orderCounts: '/order-counts',
   updateProductPayement: '/update-product-payment',
   manageTags: '/manage-tags',
   invoiceDetails: '/invoice-details',
   exportOrderTabs: '/export-order-tabs',
   orderPaymentAcceptance: '/order-payment-acceptance',
   updateBulkProduct: '/bulk-order-update',
   customerOrders: '/customerOrders',
   bulkAcceptOrders: '/bulkAcceptOrders',
   bulkUpdateOrders: '/bulkUpdateOrders'
};
