export const productEndpoints = {
    add_product: '/add-product',
    get_product: '/products',
    get_product_by_id: '/product-id',
    get_product_reports: '/product-report',
    get_product_page: '/products-page',
    get_product_names: '/product-names',
    get_product_by_slug: '/product',
    get_active_products: '/products/active',
    update_product: '/update-product',
    search_product: '/products/search',
    get_products_count: '/products/count',
    archive_product: '/products/archive',
    restore_product: '/products/restore',
    product_by_prodid: '/products/prodid',
    thumbnail_images: '/products/thumbnail-images',
    product_images: '/products/product-images',
    search_products: '/search-products',
    product_datas: '/products-data',
    products_bulk_image_upload: '/product-images',
    products_bulk_file_upload: '/product-file',
    products_bulk_thumbnail_upload: '/thumbnail-images',
    productVideo: '/product-video',
    deleteVideo: '/delete-video',
    deleteImage: '/delete-product-image',
    addProductCover: '/add-productcover',
    removeProductCover: '/remove-productcover'
}
